services:
  postgres:
    container_name: go-notify-db
    image: postgres:17.5-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  nats:
    container_name: go-notify-nats
    image: nats:2.11-alpine
    ports:
      - "4222:4222"

volumes:
  postgres_data: