// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: email.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEmail = `-- name: CreateEmail :one
INSERT INTO emails (recipient, subject, body, priority, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type CreateEmailParams struct {
	Recipient string
	Subject   string
	Body      string
	Priority  int16
	Status    DeliveryStatus
}

func (q *Queries) CreateEmail(ctx context.Context, arg CreateEmailParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createEmail,
		arg.Recipient,
		arg.Subject,
		arg.Body,
		arg.Priority,
		arg.Status,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
